# Generated by Django 4.1.3 on 2022-12-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_edited_timestamp_article_publish_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default='', max_length=600),
        ),
    ]
