# Generated by Django 4.1.3 on 2022-12-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/test')),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
