# Generated by Django 4.1.3 on 2022-12-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_article_canonical_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='canonical',
            field=models.URLField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/articles/2022/12/18'),
        ),
    ]
