# Generated by Django 4.1.3 on 2022-12-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_alter_article_canonical_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='schema1',
            field=models.JSONField(blank=True, default=str, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='schema2',
            field=models.JSONField(blank=True, default=str, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='schema3',
            field=models.JSONField(blank=True, default=str, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/articles/2022/12/21'),
        ),
    ]
