# Generated by Django 4.1.3 on 2022-12-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/profile_pics/default.jpg', upload_to='images/profile_pics'),
        ),
    ]
